### ISSUE TITLE
me again

### ISSUE THREAD

**Issue by ReplicantTerry** [nai-degen/foolfuuka_scraper#2]
found a free unmoderated service with a robust api; email hunterkeeper@linuxmail.org if you are interested in writing a port to tavern/agnai. thanks

**Comment by khanonnie** [comment]
Hi, sent you a mail from a protonmail address beginning with `kh`.

**Comment by khanonnie** [comment]
Actually the mail appears to have bounced.
```
<[hunterkeeper@linuxmail.org](mailto:hunterkeeper@linuxmail.org)>: host [mx01.gmx.com](http://mx01.gmx.com/)[74.208.5.27] said: 550
    Requested action not taken: mailbox unavailable (in reply to RCPT TO
    command)
```
Do you have another inbox?  Alternatively I can be found on the Agnai d*scord: https://discord.gg/DAn38sA8Qj
Server nick is the same as my github username.
